<a href="https://colab.research.google.com/github/cnkumar20/pytorchLearn/blob/main/Copy_of_00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)


### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch
torch.set_default_device('cuda')

X = torch.rand(size=(7, 7),device='cuda')
X,X.shape

# Create random tensor


(tensor([[0.8769, 0.4802, 0.6409, 0.5553, 0.9988, 0.8375, 0.9458],
         [0.3617, 0.9919, 0.5695, 0.0194, 0.1438, 0.0086, 0.8788],
         [0.2013, 0.9364, 0.0272, 0.2777, 0.4997, 0.1985, 0.8778],
         [0.6826, 0.7804, 0.7114, 0.9404, 0.5409, 0.7211, 0.7044],
         [0.0045, 0.6160, 0.6104, 0.8210, 0.4991, 0.2335, 0.8404],
         [0.6594, 0.2222, 0.3623, 0.3137, 0.0923, 0.4977, 0.9479],
         [0.9665, 0.4619, 0.1258, 0.3768, 0.3262, 0.4915, 0.4987]],
        device='cuda:0'),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
Y = torch.rand(size=(1,7))
Y
X.matmul(Y.T)
# Perform matrix multiplication


tensor([[3.2291],
        [2.1497],
        [1.9077],
        [3.2251],
        [2.3446],
        [1.9454],
        [1.9766]], device='cuda:0')

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors

X = torch.rand(size=(7,7))
Y = torch.rand(size=(1,7))
# Matrix multiply tensors
X.matmul(Y.T)

tensor([[2.0534],
        [2.3578],
        [1.8793],
        [1.6912],
        [2.5042],
        [2.0659],
        [1.9022]], device='cuda:0')

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
tensorA = torch.rand(size=(2,3),device='cpu').to(device)
tensorB = torch.rand(size=(2,3),device='cpu').to(device)
# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensorA.matmul(tensorB.T)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
maxA = torch.max(tensorA)
# Find min
minA = torch.min(tensorA)

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
inA = torch.argmax(tensorA)
inB = torch.argmin(tensorA)
# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensorA = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensorB = tensorA.squeeze()



# Print out tensors and their shapes
tensorA, tensorA.shape
tensorB, tensorB.shape

(tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
         0.5733], device='cuda:0'),
 torch.Size([10]))