# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch
# Create random tensor
tn = torch.tensor(7)
tn.ndim


0

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
vec = torch.tensor([7,7])
vec.shape
vec1 = torch.tensor([[7,7],[7,7]])
vec1.shape

mat1 = torch.rand(size=(7,7))
mat2 = torch.rand(size=(1,7))
#mat2 = mat2.transpose(0,1)
print(mat1)
print(mat2)

mat1.mul(mat2.T)
# Perform matrix multiplication


tensor([[0.3536, 0.0329, 0.1667, 0.2859, 0.7211, 0.1344, 0.0552],
        [0.5418, 0.2475, 0.8845, 0.9335, 0.9287, 0.3742, 0.5950],
        [0.8695, 0.8326, 0.7488, 0.9476, 0.6121, 0.6385, 0.4635],
        [0.0013, 0.0304, 0.8010, 0.4603, 0.2234, 0.3330, 0.9149],
        [0.1994, 0.1594, 0.8856, 0.6500, 0.8827, 0.2964, 0.0182],
        [0.5478, 0.4583, 0.2351, 0.6116, 0.8726, 0.5047, 0.8262],
        [0.2322, 0.1238, 0.0071, 0.5430, 0.5923, 0.8718, 0.6134]])
tensor([[0.9102, 0.3689, 0.0093, 0.8523, 0.3337, 0.9883, 0.1120]])


tensor([[3.2188e-01, 2.9968e-02, 1.5170e-01, 2.6020e-01, 6.5631e-01, 1.2232e-01,
         5.0276e-02],
        [1.9986e-01, 9.1301e-02, 3.2626e-01, 3.4434e-01, 3.4255e-01, 1.3802e-01,
         2.1946e-01],
        [8.0954e-03, 7.7517e-03, 6.9710e-03, 8.8222e-03, 5.6988e-03, 5.9447e-03,
         4.3150e-03],
        [1.1237e-03, 2.5877e-02, 6.8273e-01, 3.9234e-01, 1.9042e-01, 2.8385e-01,
         7.7980e-01],
        [6.6526e-02, 5.3184e-02, 2.9551e-01, 2.1691e-01, 2.9455e-01, 9.8900e-02,
         6.0578e-03],
        [5.4133e-01, 4.5288e-01, 2.3232e-01, 6.0440e-01, 8.6234e-01, 4.9881e-01,
         8.1655e-01],
        [2.6000e-02, 1.3857e-02, 7.9889e-04, 6.0796e-02, 6.6322e-02, 9.7611e-02,
         6.8677e-02]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)



# Create two random tensors
m1 = torch.rand(size=(7,7))
m2 = torch.rand(size=(1,7))

res = m1.matmul(m2.T)

# Matrix multiply tensors
res

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.set_default_device('cuda')
torch.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)
# Check for access to GPU

# Create two random tensors on GPU
device = 'cuda' if torch.cuda.is_available else 'cpu'
m1 = torch.rand(size=(2,3)).to(device)
m2 = torch.rand(size=(2,3)).to(device)
print(m1)
print(m2)


tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')


tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
m1.matmul(m2.T)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
max_m1 = torch.max(m1)
max_m2 = torch.max(m2)
# Find min
min_m1 = torch.min(m1)
min_m2 = torch.min(m2)


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
torch.argmax(m1)

# Find arg min
torch.argmin(m2)

tensor(1, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [17]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensorA = torch.rand(size=(1,1,1,10))


# Remove single dimensions

tensorB = tensorA.squeeze()
# Print out tensors and their shapes
tensorA, tensorA.shape
tensorB, tensorB.shape

(tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
         0.5733], device='cuda:0'),
 torch.Size([10]))

In [44]:
import numpy as np
m1 = torch.rand(size=(1,2))
print(m1)
m2 = torch.from_numpy(np.array([2,3])).to(device)
print(m2)
m1.mul(m2)

tensor([[0.7635, 0.3281]], device='cuda:0')
tensor([2, 3], device='cuda:0')


tensor([[1.5270, 0.9844]], device='cuda:0')